name: arpethick-cae
channels:
- conda-forge
- anaconda-fusion
- defaults
dependencies:
- keras
- librosa
- numpy
- pandas
- matplotlib
- theano 
- pygpu
- jupyter
- mkl-service
- pip:
  - pytest
  - pescador
